### ISSUE TITLE
Styles to ops look a little more like the old site

### ISSUE THREAD

**Issue by webmasterkai** [OOKB/acf-style#1]
- new: http://acf.cape.io/opportunities
- old: http://composersforum.org/opportunities-upcoming

**Comment by webmasterkai** [comment]
"currently a more or less raw feed, need to design it up a bit."

**Comment by bjornmeansbear** [comment]
It's close. Seeing it as an iframe on a page will make it easier at this point to figure out what else might need to be done. And then the filtering tools will probably have to be styled a bit.
